=== alekseyzubkov/mock/mock-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Mock schema",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "path",
    "result_data"
  ],
  "definitions": {
    "filterTypeSchema":{
      "type": "string",
      "enum": [
        "all",
        "any"
      ]
    },
    "filterSchema": {
      "type": "object",
      "additionalProperties": {"type":"string"}
    }
  },
  "properties": {
    "path": {
      "type": "string"
    },
    "result_data": {
      "type": "object",
      "additionalProperties": true
    },
    "method": {
      "type": "string",
      "enum": [
        "GET",
        "POST",
        "PUT",
        "DELETE"
      ]
    },
    "options": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "result_status": {
          "type": "number"
        },
        "headers_match_type": {
          "$ref": "#/definitions/filterTypeSchema"
        },
        "path_params_match_type": {
          "$ref": "#/definitions/filterTypeSchema"
        },
        "query_match_type": {
          "$ref": "#/definitions/filterTypeSchema"
        }
      }
    },
    "headers": {
      "$ref": "#/definitions/filterSchema"
    },
    "path_params": {
      "$ref": "#/definitions/filterSchema"
    },
    "query": {
      "$ref": "#/definitions/filterSchema"
    },
    "body": {
      "type": "object",
      "additionalProperties": true
    }
  }
}

=== alekseyzubkov/mock/mock-data/profile/my_data/details/V1-account-inn.json
{
  "$schema": "../../../../mock-schema.json",
  "method": "POST",
  "body": {
    "pageKey": "account-inn"
  },
  "headers": {
    "sravni-api-version": "1"
  },
  "path": "",
  "result_data": {
    "screenConfig": {
      "title": ""
    },
    "content": {
      "items": [
        {
          "type": "textStack",
          "configuration": {
            "title": "ИНН",
            "titleAlignment": "left",
            "titleColor": "dark100",
            "titleFont": "h3Headline"
          },
          "margins": {
            "start": "16",
            "end": "16"
          }
        },
        {
          "type": "spacer",
          "configuration": {
            "size": "16",
            "backgroundColor": "transparent"
          }
        },
        {
          "type": "baseListItem",
          "configuration": {
            "backgroundColor": "blue06",
            "cornerRadius": "16"
          },
          "items": [
            {
              "type": "avatar",
              "configuration": {
                "backgroundColor": "transparent",
                "size": "medium",
                "imageUrlSVG": "https://s44751.cos.ngenix.net/MobileMockService/unknown/20221110_01/image4.png",
                "imageUrlPDF": "https://s44751.cos.ngenix.net/MobileMockService/unknown/20221110_01/image4.png"
              }
            },
            {
              "type": "textStack",
              "configuration": {
                "title": "Данные с Госуслуг",
                "titleFont": "subtitleXL",
                "descriptionFont": "captionXS",
                "description": "Загружены из вашей учётной записи"
              }
            }
          ],
          "margins": {
            "start": "16",
            "end": "16"
          }
        },
        {
          "type": "spacer",
          "configuration": {
            "size": "16",
            "backgroundColor": "transparent"
          }
        },
        {
          "type": "baseBlock",
          "configuration": {
            "cornerRadius": "16",
            "backgroundColor": "dark10"
          },
          "margins": {
            "start": "16",
            "end": "16"
          },
          "items": [
            {
              "type": "spacer",
              "configuration": {
                "size": "16",
                "backgroundColor": "dark10"
              }
            },
            {
              "type": "textStack",
              "configuration": {
                "title": "781283138232",
                "titleAlignment": "left",
                "titleColor": "dark100",
                "titleFont": "bodyL",
                "titleMaxLines": "2",
                "subtitle": "Номер",
                "subtitleAlignment": "left",
                "subtitleColor": "dark60",
                "subtitleFont": "captionXS",
                "subtitleMaxLines": "1"
              },
              "margins": {
                "start": "16",
                "end": "16"
              }
            },
            {
              "type": "spacer",
              "configuration": {
                "size": "16",
                "backgroundColor": "dark10"
              }
            }
          ]
        }
      ]
    }
  }
}
